### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by silviumatei** [ZoranPandovski/BookingScraper#24]
Hi there, Excellent work, thanks a lot!
I face an issue when running it though:

The error is:
```
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\Projects\Scraper\Booking.com\bthread.py", line 15, in run
    self.process_hotels(self.session, self.offset, self.rooms, self.country)
  File "booking.py", line 56, in process_hotels
    **name = ho.find('a', {'class': 'jq_tooltip'})['title']**
  File "C:\Anaconda3\lib\site-packages\bs4\element.py", line 1071, in __getitem__
    return self.attrs[key]
KeyError: 'title'
```

This error is thrown out 11 times, for different threads.  
The line throwing the error seems to be:     **name = ho.find('a', {'class': 'jq_tooltip'})['title']**

I ran the script booking.py
It produces however a file with a list of hotels in the country.

**Comment by ZoranPandovski** [comment]
Hi @silviumatei and thanks for reporting the issue. This is fixed in the latest version. If it still doesn't work for you feel free to reopen the issue.
