### ISSUE TITLE
Following the setup instructions leads to error

### ISSUE THREAD

**Issue by Aditya94A** [ZoranPandovski/BookingScraper#47]
```
Traceback (most recent call last):
  File "booking.py", line 214, in <module>
    get_data(args.rooms, args.country, args.out_format, args.startdate, args.enddate)
  File "booking.py", line 153, in get_data
    save_data(hotels_list, out_format=out_format, country=country)
  File "booking.py", line 164, in save_data
    file = writer.output_file()
  File "C:\Projects\bookingscraper\file_writer.py", line 22, in output_file
    json.dump(list(self.data), outfile, indent=2, ensure_ascii=False)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 180, in dump
    fp.write(chunk)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u01c0' in position 23: character maps to <undefined>
```

Got this after `python booking.py`. Does it require any arguments or config changes?

**Comment by Aditya94A** [comment]
All the tests are also failing with this same output

**Comment by ZoranPandovski** [comment]
Thanks for reporting this @AdityaAnand1. It's been around 1 year since I've last used this scraper. I will try to fix this when I have free time. If you want to contribute and track the issue feel free to make PR
