### ISSUE TITLE
Bugged

### ISSUE THREAD

**Issue by pvde89** [ZoranPandovski/BookingScraper#68]
/Documents/GitHub/BookingScraper/booking.py'  && echo Exit status: $? && exit 1
Traceback (most recent call last):
  File "/Documents/GitHub/BookingScraper/booking.py", line 214, in <module>
    get_data(args.rooms, args.country, args.out_format, args.startdate, args.enddate)
  File "/Documents/GitHub/BookingScraper/booking.py", line 152, in get_data
    hotels_list: list = prep_data(rooms, country, out_format, start_date, end_date)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pascal/Documents/GitHub/BookingScraper/booking.py", line 122, in prep_data
    parsed_html.find_all("li", {"class": "sr_pagination_item"})[-1]
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range

**Comment by smama65** [comment]
Dear @ZoranPandovski , I have this problem too. Can you help us?

**Comment by ZoranPandovski** [comment]
I haven't checked this repo for a year. Can you please provide more info or steps to reproduce this?

**Comment by smama65** [comment]
Dear @ZoranPandovski, thank you for your reply. When I run booking.py file, the following error occurs 

![image](https://github.com/ZoranPandovski/BookingScraper/assets/56160498/597361b1-1312-4750-9e06-4dd05bf6bf80)

I think the code cannot extract any hotel information.

**Comment by pvde89** [comment]
It shouldn't be too difficult. As far as I noticed, Booking mainly changed their classes. 

I'm trying to locate all occurrences of the specific site and XML elements that were used before and comparing it within their current pages.

**Comment by smama65** [comment]
Dear @ZoranPandovski. Do you update the repository?

**Comment by divyakhatiyan** [comment]
@ZoranPandovski  Error "IndexError: list index out of range" is coming up while finding for this class:  "sr_pagination_item"  in the parsed html around line 134 in booking.py

Now just trying to understand, the reason for searching this class, do i need to change the url as well. Any pointer will be highly appreciated.

    all_offset = (
        parsed_html.find_all("li", {"class": "sr_pagination_item"})[-1]
        .get_text()
        .splitlines()[-1]
    )

![11 10 2024_23 00 56_REC](https://github.com/user-attachments/assets/0634dbee-e329-4e24-8287-815ed94128e7)

**Comment by webbrain-one** [comment]
Hi everyone! I just opened PR #75 to fix the bug reported in issue #68. The problem was an `IndexError: list index out of range` occurring in `booking.py` at line 122, specifically when trying to access the last pagination item with `parsed_html.find_all("li", {"class": "sr_pagination_item"})[-1]`. It looks like the code assumed pagination elements were always present, but in some cases (like when there's only one page of results), this list can be empty. The fix adds a check to ensure the pagination list has elements before accessing the last item, preventing the crash. Would appreciate any feedback or reviews!
